### ISSUE TITLE
tespy run 

### ISSUE THREAD

**Issue by HWRix** [annayqho/AnnaCannon#2]
had to replace line 67 in cannon2_infer_labels.py
       #opt.curve_fit(func, coeffs, fluxes_norm, sigma=weights, absolute_sigma = True)
by
      opt.curve_fit(func, coeffs, fluxes_norm, sigma=weights)

**Comment by annayqho** [comment]
absolute_sigma is important because it tells Python that we want to take the absolute values of our uncertainties into account. the default value is absolute_sigma = False, which means that they are only treated as relative values. 

may have to change the code so that it performs this regardless of absolute_sigma...

**Comment by annayqho** [comment]
I wrote a try/except statement that checks whether the version has absolute_sigma, and if not scales the covariance matrix by itself.
